# Generated by Django 2.1.7 on 2020-06-05 03:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_deal', models.CharField(choices=[('SALE', 'Продам'), ('BUY', 'Куплю'), ('EXCHANGE', 'Обменяю'), ('SERVICE', 'Услуга'), ('RENT', 'Оренда'), ('CLOSED', 'Закрыто')], default='SALE', max_length=8)),
                ('title', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('upped_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='ad')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flea_market.Ad')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flea_market.Ad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flea_market.Ad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='comment')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flea_market.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(choices=[('ILLEGAL', 'Сообщение содержит ссылки на незаконные или пиратские программы.'), ('AD', 'Сообщение имеет единственной целью рекламу сайтов, программ или других продуктов, товаров, услуг и пр.'), ('NOT THAT', 'Сообщение не относится к обсуждаемой теме.'), ('OTHER', 'Причина обжалования не относится ни к одной из перечисленных, используйте поле дополнительной информации.')], default='ILLEGAL', max_length=8)),
                ('text_complaint', models.TextField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flea_market.Ad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type_region', models.CharField(default='REGION', max_length=6)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flea_market.Location')),
            ],
        ),
        migrations.CreateModel(
            name='SectionProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_section', models.PositiveSmallIntegerField(default=0)),
                ('type_category', models.CharField(choices=[('CAT', 'Категория'), ('SUBCAT', 'Подкатегория')], default='CAT', max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flea_market.SectionProduction')),
            ],
        ),
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flea_market.TestUser')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flea_market.TestUser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flea_market.TestUser'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flea_market.TestUser'),
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flea_market.SectionProduction'),
        ),
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flea_market.Location'),
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flea_market.TestUser'),
        ),
    ]
