# Generated by Django 2.1.7 on 2020-04-13 21:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_categories', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
