# Generated by Django 2.1.7 on 2020-06-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='number_region',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
