# Generated by Django 2.1.7 on 2020-06-06 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0002_location_number_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities_this_region', to='flea_market.Location'),
        ),
    ]
