# Generated by Django 2.1.7 on 2020-04-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0004_auto_20200414_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_category',
            new_name='name',
        ),
    ]
