# Generated by Django 2.1.7 on 2020-04-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0006_category_type_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_category', models.CharField(choices=[('CAT', 'Категория'), ('SUBCAT', 'Подкатегория')], default='CAT', max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flea_market.Subcategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flea_market.Subcategory'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
