# Generated by Django 2.1.7 on 2020-04-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0007_auto_20200414_1853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='SectionProduction',
        ),
    ]
