# Generated by Django 2.1.7 on 2020-04-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea_market', '0008_auto_20200414_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionproduction',
            name='number_section',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
